### PR TITLE
DOC

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
@hugorichard can you activate circleci build on PRs from forks please?

> you go to project settings
> advanced
> then build PR from forks

thanks

**Comment by agramfort** [comment]
Circle had not run. Sorry I should have been explicit. Did you activate build for forks?

**Comment by hugorichard** [comment]
Yes It is active now. Yes I should have waited a bit.

**Comment by hugorichard** [comment]
There is an issue with pandoc. It is not installed and I don't have root access.

**Comment by agramfort** [comment]
so I let you finish?

>

**Comment by agramfort** [comment]
so do you need help?

>

**Comment by hugorichard** [comment]
No I think I can do it. I'll let you know.

**Comment by agramfort** [comment]
ok

you should also reconsider what is presented as an example in the gallery

**Pull request merged**
